version: "3.9"
    
services:
  db:
    image: mysql:5.7
    container_name: Cafe_XYZ
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports: 
      - 1212:3306
    environment:
      MYSQL_ROOT_PASSWORD: cafexyz
      MYSQL_DATABASE: cafe-xyz
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin

volumes:
  db_data: {}
